version: '3'
services:
  devcontainer:
    image: ghcr.io/kompiro/yadm:latest
    volumes:
      - ..:/workspace/
      - history:/home/vscode/.history
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_bank

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres-data:
  history:
