version: '3'
services:
  devcontainer:
    image: ghcr.io/kompiro/devcontainers:latest
    volumes:
      - ..:/workspace/
    network_mode: service:db
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_bank

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
