name: build and push image

on:
  workflow_dispatch:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/simplebank:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ github.repository_owner }}/simplebank
          subject-digest: ${{ github.sha }}
          push-to-registry: true
      
      - name: Build and push migrate image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: migrate
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/simplebank-migrate:latest
