name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      container: golang:1.22.5-alpine3.20
      services:
        db:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: simple_bank
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

      steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install golang migrate
        run: |
          apk add curl make
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate /usr/local/bin/migrate

      - name: Run migrations
        run: make migrate

      - name: Test
        run: make test-report

      - name: Upload Test Results
        uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: test-report.xml

      - name: Publish Test Report
        id: test-report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: test-report.xml
