name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      services:
        db:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: simple_bank
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

      steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate /usr/local/bin/migrate

      - name: Run migrations
        run: make migrate DB_SOURCE=postgresql://postgres:postgres@localhost:5432/simple_bank?sslmode=disable

      - name: Test
        run: make test-report DB_SOURCE=postgresql://postgres:postgres@localhost:5432/simple_bank?sslmode=disable

      - name: Upload Test Results
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: test-results
          path: test-report.xml

      - name: Publish Test Report
        id: test-report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: test-report.xml
          check_name: Go test report
