name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      services:
        db:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: simple_bank
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

      steps:
  
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.4
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install golang migrate
        run: |
          curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
          sudo apt install migrate=4.17.1

      - name: Run migrations
        run: make migrate

      - name: Test
        run: make test
