name: Deploy

on:
  release:
    types: [published]

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO_BASE: ghcr.io/${{ github.repository_owner }}/simplebank
      DEST_REPO_BASE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/simplebank

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker image pull ${{ env.SOURCE_REPO_BASE }}/app:main
          docker image pull ${{ env.SOURCE_REPO_BASE }}/migrate:main

      - name: Tag for Destination
        run: |
          docker image tag ${{ env.SOURCE_REPO_BASE }}/app:main ${{ env.DEST_REPO_BASE }}/app:${{ github.ref_name }}
          docker image tag ${{ env.SOURCE_REPO_BASE }}/migrate:main ${{ env.DEST_REPO_BASE }}/migrate:${{ github.ref_name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image
        run: |
          docker image push ${{ env.DEST_REPO_BASE }}/app:${{ github.ref_name }}
          docker image push ${{ env.DEST_REPO_BASE }}/migrate:${{ github.ref_name }}
