name: 'Test Report'
on:
  workflow_run:
    workflows: ['ci-test']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:

    - name: Publish Test Report
      id: test-report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: test-report.xml

